website/__init__.py
from flask import Flask
from flask_restful import Api


import logging


def create_app():

    app = Flask(__name__)
    api = Api(app)
    app.config['SECRET_KEY'] = "sdkdlkl3kjl"
    app.config.SESSION_COOKIE_SAMESITE = 'None'
    app.config.SESSION_COOKIE_SECURE = 'True'

    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
        datefmt="%m-%d %H:%M",
        handlers=[logging.StreamHandler()]
    )

    from .views import views
    from .api import Api_home, Greet, Info

    app.register_blueprint(views, url_prefix="/")
    api.add_resource(Info, '/api/info')
    api.add_resource(Api_home, '/api')
    api.add_resource(Greet, '/api/greet', '/api/greet/<string:name>')

    return app

website/views.py
from flask import Blueprint, redirect, render_template, session, request, url_for
from website import logging
from .utils import server_info

views = Blueprint('views', __name__)
logger = logging.getLogger(__name__)
readme = 'README.md'


@views.route('/')
def index():
    appVer = getAppVersion()
    serv_info = server_info()
    session["appVer"] = appVer
    logger.info(f"App Version : {appVer}")
    return render_template('index.html', title='Home', serv_info=serv_info)


@views.route("/greet", defaults={'name': 'KingKong'}, methods=['GET', 'POST'])
@views.route("/greet/<string:name>")
def greet(name):
    if request.method == 'GET':
        return render_template('greet.html', title='Greet', name=name)
    if request.method == 'POST':
        name = request.form.get('inputValue')
        if not name:
            name = "KingKong"
        return redirect(url_for('views.greet', name=name))


@views.route('/about')
def about():
    return render_template('about.html', title='About')


@views.route('/update-version')
def updateAppVersion():
    appver = request.args.get('val')
    if appver:
        with open(readme, 'r') as f:
            data = f.readlines()
        for index, line in enumerate(data):
            if 'App Version' in line:
                content = line.rstrip("\n").split(" ")
                content[-1] = f"{appver}\n"
                line = " ".join(content)
                data[index] = line

        with open(readme, 'w') as f:
            f.writelines(data)
            logger.info(f"App Version is updated : {appver}")

    return redirect(url_for('views.index'))


def getAppVersion() -> str:
    appVer = ""
    try:
        with open(readme, 'r') as f:
            data = f.readlines()
        appVer = [x.rstrip('\n').split(":")[1].split("]")
                  for x in data if 'Version' in x][0][0]
    except IndexError:
        logger.error(
            'README.md file is missing or with no "App Version" in the source code')
    return appVer

website/templates/_footer.html
<footer class="text-muted mt-5 py-5">
  <div class="container">
    <p class="float-end mb-1">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        class="bi bi-info-circle-fill"
        viewBox="0 0 16 16"
      >
        <path
          d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"
        />
      </svg>
      App Version:
      <span class="badge rounded-pill bg-light text-dark"
        >{{session['appVer']}}</span
      >
    </p>
    <p class="mb-1">&copy; Helloapp, Have a nice day!</p>
  </div>
</footer>

website/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('views.index') }}"> Helloapp</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{{ url_for('views.index') }}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.greet') }}">Greet</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

website/templates/_serv_info.html
<div class="col-lg-6 col-md-8 mx-auto">
  <div class="card">
    <h5 class="card-header">Server Info</h5>
    <div class="card-body">
      <table class="border-0 table table-sm table-striped">
        <tbody class="border-light">
          {%for k,v in serv_info.items()%}
          <tr>
            <td class="text-start">{{k.replace("_", " ")}}</td>
            <td class="text-start">{{v}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>

website/templates/about.html
{% extends 'base.html' %} {%block title%}{{title}}{%endblock%} {%block content%}

<h1>About</h1>
<p>
  I hope this web app will provide you with value and it's useful for devops and
  development. We wish you to continue keep building stuffs and progressing in
  your endeavor.
</p>
<p>Have a nice day!</p>
{%endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{{ url_for('static', filename='img/Hello-img.webp') }}"
    />
    <title>Helloapp | {%block title%} {%endblock%}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css')}}"
    />
  </head>
  <body>
    <header>{%include '_navbar.html'%}</header>
    <main class="container mb-5">{%block content%} {%endblock%}</main>
    {% include '_footer.html'%}
    <script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
  </body>
</html>

website/templates/greet.html
{% extends 'base.html' %} {%block title%}{{title}}{%endblock%} {% block content
%}
<div>
  <h1>Greetings</h1>
  <p class="py-lg-5">Hello <strong> {{name}}</strong>, Have a nice day !</p>
</div>

{%endblock%}

website/templates/index.html
{% extends 'base.html' %} {%block title%}{{title}}{%endblock%} {% block content
%}

<section class="text-center">
  <div class="row py-lg-5 mb-10 my-auto">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Welcome to Hello App !!</h1>
      <p class="lead text-muted">
        This is a test webapp with some common functionalities to test various
        needs for development, environment setup, devops tools connectivity and
        workflows.
      </p>
      <form
        action="/greet"
        method="post"
        class="row py-3 g-3 text-center d-inline-flex"
      >
        <div class="col-auto">
          <label for="inputValue" class="visually-hidden">Name</label>
          <input
            type="text"
            class="form-control"
            id="inputValue"
            name="inputValue"
            placeholder="Name"
          />
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-outline-info mb-3">Greet</button>
        </div>
      </form>
    </div>
    {%if serv_info %} {% include '_serv_info.html' %} {%endif%}
  </div>
</section>
{%endblock%}